services:
  db:
    image: 'postgres:14-alpine'
    container_name: db
    restart: always
    environment:
      - POSTGRES_DB=dyscotkeo
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
    ports:
      - "5555:5432"
  client:
    image: 'dpage/pgadmin4'
    container_name: client
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@user.com
      - PGADMIN_DEFAULT_PASSWORD=1234
    depends_on:
      - db
    ports:
      - 5050:80